### ISSUE TITLE
hi How to Add new face 

### ISSUE THREAD

**Issue by Watcharin04** [juan-csv/face_recognition_occlusion#1]
**I want to add new faces, what do I do?**

**Comment by juan-csv** [comment]
Just add the image in format .jpg with the face you want to add to the images folder

**Comment by Watcharin04** [comment]
ok Thank but now i not run code because. ImportError: No module named face_recognition

**Comment by juan-csv** [comment]
you have to run pip install face-recognition, then upload the requirements file.

**Comment by Watcharin04** [comment]
Thank you very much
